apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
  namespace: {{ .Values.namespace.name }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: todo-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80