repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry -C todo-api run black
        language: python
        require_serial: true
        args: [--config=todo-api/pyproject.toml]
        types_or: [python, pyi]

      - id: flake8
        name: flake8
        entry: poetry -C todo-api run flake8
        language: python
        require_serial: true
        args: [--config=todo-api/.flake8]
        types: [python]

      - id: isort
        name: isort
        entry: poetry -C todo-api run isort
        stages: [commit, merge-commit, push, manual]
        language: python
        require_serial: true
        args: ["--filter-files"]
        types_or: [cython, pyi, python]

      - id: mypy-src
        name: mypy-src
        entry: sh -c 'source load-env.sh && cd todo-api/src && poetry run mypy . --config-file=../pyproject.toml'
        language: system
        require_serial: true
        types_or: [python, pyi]
        pass_filenames: false

      - id: mypy-tests
        name: mypy-tests
        entry: sh -c 'source load-env.sh && cd todo-api/tests && poetry run mypy . --config-file=../pyproject.toml --explicit-package-bases'
        language: system
        require_serial: true
        types_or: [python, pyi]
        pass_filenames: false
