apiVersion: batch/v1
kind: Job
metadata:
  name: todo-api-job
spec:
  template:
    spec:
      containers:
        - name: todo-api-job-container
          image: todo-api-job
          imagePullPolicy: Never
          command: ["/bin/sh", "-c"]
          args: ["/opt/venv/bin/python ARGS_PLACEHOLDER"]
          envFrom:
            - configMapRef:
                name: todo-api-config
            - secretRef:
                name: todo-api-secret
