"""
Django settings for todo project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from config.exceptions import MissingConfiguration

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

try:
    DEBUG = os.environ["DEBUG"] == "True"
    ALLOWED_HOSTS = os.environ["ALLOWED_HOSTS"].split(",")
    DB_NAME = os.environ["DB_NAME"]
    DB_USER = os.environ["DB_USER"]
    DB_PASSWORD = os.environ["DB_PASSWORD"]
    DB_WRITER_HOST = os.environ["DB_WRITER_HOST"]
    DB_READER_HOST = os.environ["DB_READER_HOST"]
    DB_PORT = os.environ["DB_PORT"]
    TAG = os.environ["TAG"]
    BRANCH = os.environ["BRANCH"]
    COMMIT = os.environ["COMMIT"]
    SECRET_KEY = os.environ["SECRET_KEY"]
except KeyError as exc:
    raise MissingConfiguration(f"The {exc} environment variable is required.")


# Application definition

INSTALLED_APPS: list[str] = ["todos"]

MIDDLEWARE: list[str] = []

ROOT_URLCONF = "config.urls"


WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_WRITER_HOST,
        "PORT": DB_PORT,
    },
    "reader": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_READER_HOST,
        "PORT": DB_PORT,
    },
}


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {},
    },
]
