apiVersion: batch/v1
kind: Job
metadata:
  name: backend-job
spec:
  template:
    spec:
      containers:
        - name: backend-job-container
          image: backend-job
          imagePullPolicy: Never
          command: ["/bin/sh", "-c"]
          args: ["/opt/venv/bin/python ARGS_PLACEHOLDER"]
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          volumeMounts:
            - name: backend-src-volume
              mountPath: /app/src
            - name: backend-tests-volume
              mountPath: /app/tests
      restartPolicy: Never
      volumes: # local only
        - name: backend-src-volume
          hostPath:
            path: /project/backend/src
            type: Directory
        - name: backend-tests-volume
          hostPath:
            path: /project/backend/tests
            type: Directory
