apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api-db
  template:
    metadata:
      labels:
        app: todo-api-db
    spec:
      containers:
        - name: postgres
          image: public.ecr.aws/docker/library/postgres:15.4
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: todo-api-config
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: todo-api-config
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-api-secret
                  key: DB_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: todo-api-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: todo-api-db-storage
          persistentVolumeClaim:
            claimName: todo-api-db-pvc
