apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api-container
          image: todo-api
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: todo-api-config
            - secretRef:
                name: todo-api-secret
          args:
            [
              "-m",
              "uvicorn",
              "--host",
              "0.0.0.0",
              "config.asgi:application",
              "--reload",
            ]
          volumeMounts:
            - name: todo-api-volume
              mountPath: /app/src
      volumes: # local only
        - name: todo-api-volume
          hostPath:
            path: /project/todo-api/src
            type: Directory
